<Project>
  <PropertyGroup>
    <MauiUnoTarget>true</MauiUnoTarget>
    <RuntimeIdentifier Condition="'$(UnoSampleRuntimeIdentifier)' != ''">$(UnoSampleRuntimeIdentifier)</RuntimeIdentifier>
    <_MauiUnoBuildProperties>MauiUnoTarget=true;IncludeAndroidTargetFrameworks=false;IncludeIosTargetFrameworks=false;IncludeMacCatalystTargetFrameworks=false;IncludeMacOSTargetFrameworks=false;IncludeTizenTargetFrameworks=false;IncludeWindowsTargetFrameworks=false;RuntimeIdentifier=$(RuntimeIdentifier);SelfContained=false</_MauiUnoBuildProperties>
    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <UnoDisableHotRestartHelperGeneration>true</UnoDisableHotRestartHelperGeneration>
    <NoWarn>$(NoWarn);Uno0001;IL2072;IL2111;RS0030</NoWarn>
  </PropertyGroup>

  <ItemDefinitionGroup>
    <ProjectReference>
      <GlobalPropertiesToRemove>RuntimeIdentifiers;SelfContained</GlobalPropertiesToRemove>
    </ProjectReference>
  </ItemDefinitionGroup>

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)..\..\..\Core\src\Core.csproj"
      SkipGetTargetFrameworkProperties="true"
      SetTargetFramework="TargetFramework=net10.0;$(_MauiUnoBuildProperties)" />
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)..\..\..\Graphics\src\Graphics\Graphics.csproj"
      SkipGetTargetFrameworkProperties="true"
      SetTargetFramework="TargetFramework=net10.0;$(_MauiUnoBuildProperties)" />
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)..\..\src\Core\Controls.Core.csproj"
      SkipGetTargetFrameworkProperties="true"
      SetTargetFramework="TargetFramework=net10.0;$(_MauiUnoBuildProperties)" />
    <ProjectReference
      Include="$(MSBuildThisFileDirectory)..\..\src\Xaml\Controls.Xaml.csproj"
      SkipGetTargetFrameworkProperties="true"
      SetTargetFramework="TargetFramework=net10.0;$(_MauiUnoBuildProperties)" />
  </ItemGroup>

  <Target Name="_ConfigureMauiUnoRestoreGraph"
          BeforeTargets="_GenerateRestoreProjectPathWalk;_GenerateRestoreGraph"
          Condition="'$(MauiUnoTarget)' == 'true'">
    <PropertyGroup>
      <_GenerateRestoreGraphProjectEntryInputProperties>
        $(_GenerateRestoreGraphProjectEntryInputProperties);
        $(_MauiUnoBuildProperties)
      </_GenerateRestoreGraphProjectEntryInputProperties>
    </PropertyGroup>
  </Target>
</Project>
