<Project>
  <PropertyGroup>
    <UnoMauiSdkRoot Condition="'$(UnoMauiSdkRoot)' == ''">$(MSBuildThisFileDirectory)..\</UnoMauiSdkRoot>
    <UnoMauiUseSource>false</UnoMauiUseSource>
    <UnoMauiPackageReferencesProvided>true</UnoMauiPackageReferencesProvided>
    <UnoMauiPackageVersion Condition="'$(UnoMauiPackageVersion)' == ''">10.0.100-dev</UnoMauiPackageVersion>
    <UnoMauiUnoVersion Condition="'$(UnoMauiUnoVersion)' == ''">6.7.0-dev.704</UnoMauiUnoVersion>
    <UnoMauiAndroidRuntimeVersion Condition="'$(UnoMauiAndroidRuntimeVersion)' == ''">$(UnoMauiUnoVersion)</UnoMauiAndroidRuntimeVersion>
    <UnoMauiWasmRuntimeVersion Condition="'$(UnoMauiWasmRuntimeVersion)' == ''">$(UnoMauiUnoVersion)</UnoMauiWasmRuntimeVersion>
    <UnoMauiWasmBootstrapVersion Condition="'$(UnoMauiWasmBootstrapVersion)' == ''">10.0.96</UnoMauiWasmBootstrapVersion>
    <UnoMauiAutoEnableAccessibility Condition="'$(UnoMauiAutoEnableAccessibility)' == ''">false</UnoMauiAutoEnableAccessibility>
    <UnoMauiEnableStartupTracing Condition="'$(UnoMauiEnableStartupTracing)' == ''">false</UnoMauiEnableStartupTracing>
    <UnoMauiOptimizeWasmRuntime Condition="'$(UnoMauiOptimizeWasmRuntime)' == ''">true</UnoMauiOptimizeWasmRuntime>
    <UnoMauiWasmAot Condition="'$(UnoMauiWasmAot)' == ''">false</UnoMauiWasmAot>
    <UnoMauiAndroidProfiledAot Condition="'$(UnoMauiAndroidProfiledAot)' == ''">false</UnoMauiAndroidProfiledAot>
    <UnoMauiAndroidExtractNativeLibs Condition="'$(UnoMauiAndroidExtractNativeLibs)' == ''">true</UnoMauiAndroidExtractNativeLibs>
    <UnoMauiAndroidLargeHeap Condition="'$(UnoMauiAndroidLargeHeap)' == ''">false</UnoMauiAndroidLargeHeap>
  </PropertyGroup>

  <ItemGroup>
    <CompilerVisibleProperty Include="MSBuildProjectFullPath" />
    <CompilerVisibleProperty Include="MSBuildProjectDirectory" />
  </ItemGroup>
</Project>
