<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Maui.Controls.Sample.Uno</RootNamespace>
    <RollForward>Major</RollForward>
    <IsUnoHead>true</IsUnoHead>
  </PropertyGroup>

  <Import Project="..\MauiUnoSample.props" />

  <ItemGroup>
    <PackageReference Include="Uno.WinUI.Runtime.Skia.Linux.FrameBuffer" />
    <PackageReference Include="Uno.WinUI.Runtime.Skia.MacOS" />
    <PackageReference Include="Uno.WinUI.Runtime.Skia.Win32" />
    <PackageReference Include="Uno.WinUI.Runtime.Skia.X11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\Shared\Controls.Sample.Embedding.Uno.Shared.csproj"
      SkipGetTargetFrameworkProperties="true"
      SetTargetFramework="TargetFramework=net10.0;$(_MauiUnoBuildProperties)" />
  </ItemGroup>

</Project>
